language: c++

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages: lcov

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
 #Install libconfig
  - wget https://hyperrealm.github.io/libconfig/dist/libconfig-1.7.2.tar.gz
  - tar -xvzf libconfig-1.7.2.tar.gz
  - pushd libconfig-1.7.2 && ./configure && make && sudo make install && popd
  
  - sudo pip install codecov

script:
  - mkdir -p build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make install
  - ctest -V

after_success: 
  #Codecov
  # Create lcov report
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' '*/tests/*' '*/external/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  # - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
